name: books_bart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  order_repository:
    path: packages/order_repository
  form_inputs:
    path: packages/form_inputs
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_slidable: ^3.1.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  collection: ^1.19.0
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  flow_builder: ^0.1.0
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
