name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  meta: ^1.15.0
  cache:
    path: ../cache

dev_dependencies:
  firebase_auth_platform_interface: ^7.4.10
  firebase_core_platform_interface: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8